<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="<?php echo $this->url(array("controller"=>"Dossierordinaire","action"=>"index")) ?>">Dossiers Ordinaires</a></li>
  <li role="presentation"><a href="<?php echo $this->url(array("controller"=>"Instruction","action"=>"index")) ?>">Instructions</a></li>
  <li role="presentation"><a href="<?php echo $this->url(array("controller"=>"Reaction","action"=>"index")) ?>">Réactions</a></li>
  <li role="presentation" ><a href="<?php echo $this->url(array("controller"=>"Avis","action"=>"index")) ?>">Avis PM</a></li>
</ul>

<div class="row" style="margin-left : 20px; margin-top:10px">
	<div class="col-xs-12"> 
		<div class="row" >
            <a href="<?php echo $this->url(array("controller"=>"Dossierordinaire","action"=>"ajouter")) ?>" class="btn btn-success" >Ajouter</a>
		</div>
		<div class="row" style="margin-top:10px">
		<table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Structure</th>
                <th>Objet</th>
                <th>Statut</th>
                <th>Synthèse</th>
                <th>Réference corresp.</th>
                <th>Date corresp.</th>
                <th>Observations</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->listeDossier as $dossier) : ?>
                <tr>
                    <td><?php if($dossier->sigleStructure) echo ($dossier->sigleStructure) ; else echo ($dossier->nomStructure); ?></td>
                    <td><?php echo utf8_encode($dossier->objetDossierO); ?></td>
                    <td><?php echo utf8_encode($dossier->libStatut); ?></td>
                    <td><?php echo utf8_encode($dossier->syntheseDossierO); ?></td>
                    <td><?php echo utf8_encode($dossier->refCorrespondance); ?></td>
                    <td><?php echo $dossier->dateCorrespondance; ?></td>
                    <td><?php echo utf8_encode($dossier->observationDossierO); ?></td>
                    <td><a title="modifier" href="<?php echo $this->url(array("controller"=>"Dossierordinaire","action"=>"modifier", "id"=>$dossier->idDossierO )) ?>"><span class="glyphicon glyphicon-edit"> </span></a></td>
                    <td><a title="supprimer" href="<?php echo $this->url(array("controller"=>"Dossierordinaire","action"=>"supprimer", "id"=>$dossier->idDossierO )) ?>"><span class="glyphicon glyphicon-remove"> </span></a></td>
                    <td><a title="Ajouter agents" href="<?php echo $this->url(array("controller"=>"Dossierordinaire","action"=>"agent", "id"=>$dossier->idDossierO, "idstr"=>$dossier->idStructure )) ?>"><span class="glyphicon glyphicon-user"> </span></a></td>
                    

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
    $('#example').DataTable( {
        "language": {
            "lengthMenu": "Affichage _MENU_   par page",
            "zeroRecords": "Aucune donnée trouvée",
            "info": "Page _PAGE_ sur _PAGES_",
            "infoEmpty": "Aucune donnée à afficher",
            "infoFiltered": "(filteré à partir de _MAX_ enregistrements)",
            "search": "Recherche ",
        }
    } );
} );
</script>