<?php if($this->etat == 1) { ?>
	<div class="alert alert-success alert-dismissible" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<strong>Opération effectuée avec succès ! </strong>
	</div>
<?php } elseif($this->etat == -1) { ?>
	<div class="alert alert-danger alert-dismissible" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<strong>Opération echouée ! </strong>
	</div>
<?php } ?>

<div class="row" style="margin-left : 20px; margin-top:10px">
	<div class="col-xs-12"> 
		<div class="row" >
            <a href="<?php echo $this->url(array("controller"=>"Dossiercm","action"=>"index")) ?>" class="btn btn-primary" >Liste dossiers</a>
		</div>
    </div>

<form style="margin-top:20px;margin-left:5px" action="<?php echo $this->url(array("controller"=>"Dossiercm","action"=>"ajouter")) ?>" method="Post" enctype="multipart/form-data">
<div class="row" style="margin-bottom:0px">
	<div class="col-xs-12" style="margin-top:10px">
		<h3 style="margin: 0px; padding-top: 0px;font-weight: bold;text-transform: uppercase;">Ajout Dossiers de conseil des ministres</h3>
		<div class="row" style="border:1px solid #D1DCF5;margin:2px 0 0 0;padding:10px;">
		<div class="row" style="margin-top:2px">
            	<div class="col-xs-6" >
                	<span style="font-weight: bold;">Structure * </span>
					<select class="form-control" name="idStructure" required="">
						<option> </option>
							<?php foreach($this->listeStr as $str) : ?>
								<option value="<?php echo $str->idStructure ?> "> <?php if($str->sigleStructure) echo $str->sigleStructure; else echo $str->nomStructure; ?> </option>
							<?php endforeach; ?>
					</select>
				</div>
            	<div class="col-xs-6" >
                	<span style="font-weight: bold;">Agent traitant * </span>
					<select class="form-control" name="idAgent" required="">
						<option> </option>
							<?php foreach($this->listeag as $agent) : ?>
								<option value="<?php echo $agent->idAgent; ?> "> <?php echo (utf8_encode($agent->nomAgent)." ".utf8_encode($agent->prenomAgent) );?> </option>
							<?php endforeach; ?>
					</select>
				</div>
        </div>

			<div class="row" style="margin-top:2px">
            	<div class="col-xs-4" >
                	<span style="font-weight: bold;">Type * </span>
					<select class="form-control" name="idType" required="">
						<option> </option>
							<?php foreach($this->listetdc as $tdc) : ?>
								<option value="<?php echo $tdc->idType ?> "> <?php echo utf8_encode($tdc->libType);?> </option>
							<?php endforeach; ?>
					</select>
				</div>
				<div class="col-xs-4" >
                    <span style="font-weight: bold;">Numero SGGCM *</span>
                    <input class="form-control" name="numeroSGGCM" type="text" required=""  />
				</div>
				<div class="col-xs-4" >
                    <span style="font-weight: bold;">Date Conseil des ministres * </span>
                     <input class="form-control" name="dateCM" type="date" required=""/>
                </div>
        	</div>
			<div class="row" style="margin-top:2px">
				<div class="col-xs-12" >
                    <span style="font-weight: bold;">Objet *</span>
                    <input class="form-control" name="objetDossierCM" type="text" required="" />
                </div>
			</div>
			<div class="row" style="margin-top:2px">

				<div class="col-xs-6" >
                    <span style="font-weight: bold;">Réference du dossier CM *</span>
                    <input class="form-control" name="refDossierCM" type="text" required=""/>
                </div>
				<div class="col-xs-6" >
                    <span style="font-weight: bold;">Réference du texte adopté *</span>
                    <input class="form-control" name="refTexteAdopte" type="text" required="" />
                </div>
			</div>
			<div class="row" style="margin-top:2px">
				<div class="col-xs-4" >
                    <span style="font-weight: bold;">Date de signature * </span>
                     <input class="form-control" name="dateSignature" type="date" required="" />
                </div>
				<div class="col-xs-8" >
                    <span style="font-weight: bold;">Décision *</span>
                    <input class="form-control" name="decisionCM" type="text" required="" />
                </div>
			</div>
			<div class="row" style="margin-top:2px">
				<div class="col-xs-6" >
                    <span style="font-weight: bold;">Synthèse *</span>
                    <textarea class="form-control" name="syntheseDossierCM" required="" rows="5"></textarea>
                </div>
                <div class="col-xs-6" >
                    <span style="font-weight: bold;">Observation </span>
					<textarea class="form-control" name="observationCM" rows="5"></textarea>
                </div>
			</div>
		</div>
	</div>
    </div>
<div class=" row" style="margin-top:20px">
	<div class="col-xs-12" style="background-color: #54B944;height:45px;text-align:center">
		<input type="submit" value="Enregistrer" class="btn btn-primary" style="border: 1px solid #FFFFFF; background-color: #54B944; border-radius: 0px;margin-top:5px;color:white" />
		<input type="reset" name="annuler" value="Annuler" class="btn btn-primary" style="border: 1px solid #FFFFFF; background-color:#54B944; border-radius: 0px;margin-top:5px;color:white" />
	</div>
</div>
</form>
</div>

