<div class="row" style="margin-left : 20px; margin-top:10px">
	<div class="col-sm-12"> 
		<div class="row" >
            <a href="<?php echo $this->url(array("controller"=>"Dossiercm","action"=>"ajouter")) ?>" class="btn btn-success">Ajouter</a>
		</div>
        <div class="row" style="margin-top:10px">
        <fieldset>
            <legend>
        <h3 style="margin: 0px; padding-top: 0px;font-weight: bold;text-transform: uppercase;">Liste des Dossiers de conseil des ministres</h3>
        </legend>
        <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Structure</th>
                <th>Agent</th>
                <th>Type</th>
                <th>Objet</th>
                <th>Numero SGGCM</th>
                <th>Synthèse</th>
                <th>Réference</th>
                <th>Décision</th>
                <th>Texte adopté</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->listeDossier as $dossier) : ?>
                <tr>
                    <td><?php if($dossier->sigleStructure){ echo $dossier->sigleStructure; } else {echo utf8_encode($dossier->nomStructure);} ?></td>
                    <td><?php echo ($dossier->nomAgent." ".utf8_encode($dossier->prenomAgent)); ?></td>
                    <td><?php echo $dossier->libType; ?></td>
                    <td><?php echo $dossier->objetDossierCM; ?></td>
                    <td><?php echo $dossier->numeroSGGCM; ?></td>
                    <td><?php echo $dossier->syntheseDossierCM; ?></td>
                    <td><?php echo $dossier->refDossierCM; ?></td>
                    <td><?php echo $dossier->decisionCM; ?></td>
                    <td><?php echo $dossier->refTexteAdopte; ?></td>
                    <td><a href="<?php echo $this->url(array('controller'=>'Dossiercm','action'=>'modifier','id'=>$dossier->idDossierCM)) ?>"><span class="glyphicon glyphicon-edit"  alt="modifier" title="Modifier"> </span></a>
                    <a href="<?php echo $this->url(array('controller'=>'Dossiercm','action'=>'supprimer','id'=>$dossier->idDossierCM)) ?>"><span class="glyphicon glyphicon-remove" alt="supprimer" title="supprimer"> </span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </fieldset>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
    $('#example').DataTable( {
        "language": {
            "lengthMenu": "Affichage _MENU_   par page",
            "zeroRecords": "Nothing found - Aucune donnée trouvée",
            "info": "Page _PAGE_ sur _PAGES_",
            "infoEmpty": "Aucune donnée à afficher",
            "infoFiltered": "(filtered from _MAX_ total records)",
            "search": "Recherche ",
        }
    } );
} );
</script>