<!DOCTYPE html>
<html lang="fr">
<head>
			<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
			<link rel="shortcut icon" type="image/png" href="favicon.png"/>
			<?php
	    		echo $this->headMeta(). PHP_EOL;
	    		echo $this->headTitle(). PHP_EOL;
	    		echo $this->headLink(). PHP_EOL;
	    		echo $this->headScript(). PHP_EOL;
        
        	$this->jQuery()
    
                	->setLocalPath($this->baseUrl().'/js/jquery/jquery-3.5.1.min.js')
        	    		->enable();
          echo $this->jQuery();
	
    			echo $this->headMeta(); 
          echo $this->headTitle(); 
          
          echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/bootstrap/css/bootstrap.min.css');
          //echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/bootstrap/css/jquery.dataTables.min.css'); 
        	//echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/jquery.rtnotify.css'); 
          echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/multiselectable.css'); 
   			?>


         <script type="text/javascript" language="javascript" src="<?php  echo $this->baseUrl().'/js/bootstrap/js/bootstrap.min.js';?>"></script>
         <script type="text/javascript" language="javascript" src="<?php  echo $this->baseUrl().'/js/jquery/jquery.dataTables.min.js';?>"></script>
         <script type="text/javascript" language="javascript" src="<?php  echo $this->baseUrl().'/js/bootstrap/js/dataTables.bootstrap.min.js';?>"></script>
        	<script type="text/javascript" language="javascript" src="<?php  echo $this->baseUrl().'/js/jquery.rtnotify.js';?>"></script>
        	<script type="text/javascript" language="javascript" src="<?php  echo $this->baseUrl().'/js/sha1.js';?>"></script>
          <script type="text/javascript" language="javascript" src="<?php  echo $this->baseUrl().'/js/autoNumeric.js';?>"></script>
          <script type="text/javascript" language="javascript" src="<?php  echo $this->baseUrl().'/js/multiselectable.js';?>"></script>
          <script type="text/javascript" language="javascript" src="<?php  echo $this->baseUrl().'/js/keyfilter/keyfilter.js';?>"></script>
        
		</head>
<body>
<nav class="navbar navbar-default" style="background-color:#1e8449; ">
  <div class="container-fluid">
  <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"  style="color:#FFF">Administration <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="#"> Utilisateurs</a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Profil </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Role </a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color:#FFF">Paramètres <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><a class="dropdown-item" href=""> Structure</a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="<?php echo $this->url(array("controller"=>"Typestructure","action"=>"index")) ?>" id="typestructure"> Type Structure</a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Responsable Structure </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Agents </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Departement</a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Fonction</a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Statut Dossier</a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Type des dossiers en conseils</a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Instance de répresentation </a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color:#FFF">Programme <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="<?php echo $this->url(array("controller"=>"Pta","action"=>"index")) ?>"> Plan de Travail Annuel</a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Programme budgetaire </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Activités </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Domaine </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Actions </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Indicateurs </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Lettre de missions </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="#"> Priorités lettre de missions </a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color:#FFF">Dossiers <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="<?php echo $this->url(array("controller"=>"Dossierordinaire","action"=>"index")) ?>"> Ordinaires</a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="<?php echo $this->url(array("controller"=>"Dossiercm","action"=>"index")) ?>">  Conseils des ministres </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="<?php echo $this->url(array("controller"=>"Dossiercc","action"=>"index")) ?>"> Conseils de cabinet </a></li>
          <li role="separator" class="divider"></li>
		  <li><a class="dropdown-item" href="<?php echo $this->url(array("controller"=>"Compterenduinstance","action"=>"index")) ?>"> Comptes rendus des instances </a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav"> <li class="nav-item"><a class="nav-link" href="#" style="color:#FFF"> Statistique </a></li></ul>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" style="color:#FFF">Bienvenue OUEDRAOGO Saïdou</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color:#FFF">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Modifier son compte</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="<?php echo $this->url(array("controller"=>"connexion","action"=>"deconnexion")) ?>">Deconnexion</a></li>
            
            
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<section id="corps" class="col-xs-9">
    <?php echo $this->layout()->content; ?>
</section>
</body>
</html>

<script>
     var $corps = $('#corps');
     $('#typestructure').on('click',function(){
        $corps.load("typestructure/index");
     })
</script>
