<div class="row" style="margin-left : 20px; margin-top:10px">
	<div class="col-xs-12"> 
		<div class="row" >
            <a href="<?php echo $this->url(array("controller"=>"Compterenduinstance","action"=>"ajouter")) ?>" class="btn btn-success">Ajouter</a>
		</div>
        <div class="row" style="margin-top:10px">
        <fieldset>
            <legend>
        <h3 style="margin: 0px; padding-top: 0px;font-weight: bold;text-transform: uppercase;">Liste des comptes rendus d'instance</h3>
        </legend>
        <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
				<th>Structure</th>
                <th>Instance</th>
                <th>Objet</th>
                <th>Décisions</th>
                <th>Perspectives</th>
                <th>Date de début</th>
                <th>Date de fin</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->listeCR as $cr) : ?>
                <tr>
                <td><?php if($cr->sigleStructure) echo $cr->sigleStructure; else echo utf8_encode($cr->nomStructure); ?></td>
                    <td><?php echo utf8_encode($cr->libInstance); ?></td>
                    <td><?php echo utf8_encode($cr->objetCR); ?></td>
                    <td><?php echo utf8_encode($cr->decision); ?></td>
                    <td><?php echo utf8_encode($cr->perspective); ?></td>
                    <td><?php echo $cr->dateDebut; ?></td>
                    <td><?php echo $cr->dateFin; ?></td>
                    <td><a href="<?php echo $this->url(array('controller'=>'Compterenduinstance','action'=>'modifier','id'=>$cr->idCR)) ?>"><span class="glyphicon glyphicon-edit"> </span></a>
                    <a href="<?php echo $this->url(array('controller'=>'Compterenduinstance','action'=>'supprimer','id'=>$cr->idCR)) ?>"><span class="glyphicon glyphicon-remove"> </span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </fieldset>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
    $('#example').DataTable( {
        "language": {
            "lengthMenu": "Affichage _MENU_   par page",
            "zeroRecords": "Nothing found - Aucune donnée trouvée",
            "info": "Page _PAGE_ sur _PAGES_",
            "infoEmpty": "Aucune donnée à afficher",
            "infoFiltered": "(filtered from _MAX_ total records)",
            "search": "Recherche ",
        }
    } );
} );
</script>