<form method="Post" action="<?php echo $this->url(array('action'=>'supprimer')); ?>">
<div class="modal" id="confirmationDossier">
    <div class="modal-dialog modal-sm">
        <div class="modal-content" style="background-color : whitesmoke">
                <div class="modal-body">
				<?php foreach($this->cr as $cr) : ?>
					<span class="glyphicon glyphicon-exclamation-sign" style="color: #f0ad4e">
					<label style="font-size: 18;">Etes vous sûr de vouloir supprimer le compte rendu ayant pour objet:"<?php echo utf8_encode($cr->objetCR);?>" ? </label></span>
					<input type="hidden" name="id" value="<?php echo $this->id; ?>"/>
				<?php endforeach;?>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-success " value="OUI">
				    <a href="<?php echo $this->url(array("controller"=>"Compterenduinstance","action"=>"index" )) ?>"  class="btn btn-danger" > NON</a>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

<script>
	$(document).ready(function(){
		$('#confirmationDossier').modal()
	});
</script>
