<?php if($this->etat == 1) { ?>
	<div class="alert alert-success alert-dismissible" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<strong>Opération effectuée avec succès ! </strong>
	</div>
<?php } elseif($this->etat == -1) { ?>
	<div class="alert alert-danger alert-dismissible" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<strong>Opération echouée ! </strong>
	</div>
<?php } ?>

<div class="row" style="margin-left : 20px; margin-top:10px">
	<div class="col-xs-12"> 
		<div class="row" >
            <a href="<?php echo $this->url(array("controller"=>"Pta","action"=>"index")) ?>" class="btn btn-primary" >Liste dossiers</a>
		</div>
    </div>

<form style="margin-top:20px;margin-left:5px" action="<?php echo $this->url(array("controller"=>"Pta","action"=>"ajouter")) ?>" method="Post" enctype="multipart/form-data">
<div class="row" style="margin-bottom:0px">
	<div class="col-xs-12" style="margin-top:10px">
		<h3 style="margin: 0px; padding-top: 0px;font-weight: bold;text-transform: uppercase;">Ajout de Plan de Travail Annuel (PTA)</h3>
		<?php foreach($this->dossier as $dossier ) : ?>
			<input type="hidden" name="idPTA" value="<?php echo $this->id ?>" />
		<div class="row" style="border:1px solid #D1DCF5;margin:2px 0 0 0;padding:10px;">
			<div class="row" style="margin-top:2px">

            	<div class="col-xs-4" >
                	<span style="font-weight: bold;">Année * </span>
					<select class="form-control" name="idAnnee" required="">
					<option value="<?php echo $dossier->idAnnee ?>"><?php echo $dossier->annee; ?> </option>
					<?php  foreach($this->listean as $an) : 
									if($an->idAnnee != $dossier->idAnnee) :
					?>
									<option value="<?php echo $an->idAnnee ?> "> <?php echo $an->annee; ?> </option>
							<?php endif; endforeach; ?>
					</select>
				</div>
				<div class="col-xs-8" >
                    <span style="font-weight: bold;">PTA *</span>
                    <input class="form-control" name="libPTA" type="text" required=""  />
				</div>
        	</div>

			<div class="row" style="margin-top:2px">

				<div class="col-xs-4" >
                    <span style="font-weight: bold;">Date de transmission *</span>
                    <input class="form-control" name="dateTransmission" type="date" required=""  />
				</div>
				<div class="col-xs-8" >
                    <span style="font-weight: bold;">Reférences de correspondance * </span>
                     <input class="form-control" name="refCorrespondance" type="text" required=""/>
                </div>
        	</div>

		</div>
		<?php endforeach;?>
	</div>
</div>
<div class=" row" style="margin-top:20px">
	<div class="col-xs-12" style="background-color: #54B944;height:45px;text-align:center">
		<input type="submit" value="Enregistrer" class="btn btn-primary" style="border: 1px solid #FFFFFF; background-color: #54B944; border-radius: 0px;margin-top:5px;color:white" />
		<input type="reset" name="annuler" value="Annuler" class="btn btn-primary" style="border: 1px solid #FFFFFF; background-color:#54B944; border-radius: 0px;margin-top:5px;color:white" />
	</div>
</div>
</form>
</div>

