<?php if($this->etat == 1) { ?>
	<div class="alert alert-success alert-dismissible" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<strong>Opération effectuée avec succès ! </strong>
	</div>
<?php } elseif($this->etat == -1) { ?>
	<div class="alert alert-danger alert-dismissible" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<strong>Opération echouée ! </strong>
		  <?php echo $this->erreur; ?>
	</div>
<?php } ?>
<ul class="nav nav-tabs">
  <li role="presentation" ><a href="<?php echo $this->url(array("controller"=>"Dossierordinaire","action"=>"index")) ?>">Dossiers Ordinaires</a></li>
  <li role="presentation" ><a href="<?php echo $this->url(array("controller"=>"Instruction","action"=>"index")) ?>">Instructions</a></li>
  <li role="presentation" class="active"><a href="<?php echo $this->url(array("controller"=>"Reaction","action"=>"index")) ?>">Réactions</a></li>
  <li role="presentation" ><a href="<?php echo $this->url(array("controller"=>"Avis","action"=>"index")) ?>">Avis PM</a></li>
</ul>

<div class="row" style="margin-left : 20px; margin-top:10px">
	<div class="col-xs-12"> 
		<div class="row" >
            <a href="<?php echo $this->url(array("controller"=>"Reaction","action"=>"index")) ?>" class="btn btn-primary" >Liste reactions</a>
		</div>
	</div>
	<?php foreach($this->reaction as $react) : ?>
<form style="margin-top:20px;margin-left:5px" action="<?php echo $this->url(array("controller"=>"Reaction","action"=>"modifier")) ?>" method="Post" enctype="multipart/form-data">
<div class="row" style="margin-bottom:0px">
	<div class="col-xs-12" style="margin-top:10px">
		<h5 style="margin: 0px; padding-top: 0px;font-weight: normal;text-transform: uppercase;">Mise à jour réaction</h5>
		<div class="row" style="border:1px solid #D1DCF5;margin:2px 0 0 0;padding:10px;">
			<div class="row" style="margin-top:2px">
            	<div class="col-xs-4" >
                	<span style="font-weight: bold;">Structure * </span>
					<select class="form-control" name="idstr" id="str" required="" >
						<option <?php echo $react->idStructure ?> > <?php if($react->sigleStructure) echo utf8_encode($react->sigleStructure); else echo utf8_encode($react->nomStructure); ?> </option>
							<?php foreach($this->listeStr as $str) : 
									if($str->idStructure != $react->idStructure) :
							?>
								<option value="<?php echo $str->idStructure ?> "> <?php if($str->sigleStructure) echo utf8_encode($str->sigleStructure); else echo utf8_encode($str->nomStructure); ?> </option>
							<?php endif; endforeach; ?>
					</select>
				</div>
				<div class="col-xs-8" id="loaddossier">
                	<span style="font-weight: bold;">Dossier * </span>
					<select class="form-control" name="iddossier" id="iddossier" required="" >
						<option value="<?php echo $react->idDossierO ?>" > <?php echo utf8_encode($react->objetDossierO) ?> </option>
						<?php foreach($this->listedossier as $dossier) : 
									if($dossier->idDossierO != $react->idDossierO) :
							?>
								<option value="<?php echo $dossier->idDossierO ?> "> <?php echo utf8_encode($dossier->objetDossierO) ?> </option>
						<?php endif; endforeach; ?>
							
					</select>
				</div>
        	</div>
			<div class="row" style="margin-top:2px">
				<div class="col-xs-12" id="loadinstruction">
                	<span style="font-weight: bold;">Instruction * </span>
					<select class="form-control" name="idins" required="" >
						<option  value="<?php echo $react->idInstruction ?> " > <?php echo ($react->instruction) ?> </option>
						<?php foreach($this->listeIns as $ins) : 
									if($ins->idInstruction != $react->idInstruction) :
							?>
								<option value="<?php echo $ins->idInstruction ?> "> <?php echo ($ins->instruction) ?> </option>
						<?php endif; endforeach; ?>
							
					</select>
				</div>
			</div>
			<div class="row" style="margin-top:2px">
				<div class="col-xs-6" >
                    <span style="font-weight: bold;">Suite donnée *</span>
					<textarea class="form-control" name="reaction" required=""><?php echo $react->suiteDonnee ?></textarea>
                </div>
                <div class="col-xs-6" >
					<span style="font-weight: bold;">Observation </span>
					<textarea class="form-control" name="observation" ><?php echo $react->observation ?> </textarea>
                </div>
			</div>
			<div class="row" style="margin-top:2px">
				<div class="col-xs-6" >
                    <span style="font-weight: bold;">ref. corresp. *</span>
                    <input type="text" class="form-control" name="refcoresp" value="<?php echo $react->refCorrepReaction ?>" required="" />
                </div>
                <div class="col-xs-6" >
                    <span style="font-weight: bold;">Date corresp. *</span>
					<input type="date" class="form-control" name="datecoresp" value="<?php echo $react->dateCorrespReaction ?>" required="" />
					<input type="hidden" name="id" value="<?php echo $this->id ?>" /> 
                </div>
			</div>
		</div>
	</div>
    </div>
<div class=" row" style="margin-top:20px">
	<div class="col-xs-12" style="background-color: #54B944;height:45px;text-align:center">
		<input type="submit" value="Modifier" class="btn btn-primary" style="border: 1px solid #FFFFFF; background-color: #54B944; border-radius: 0px;margin-top:5px;color:white" />
		<input type="reset" name="annuler" value="Annuler" class="btn btn-primary" style="border: 1px solid #FFFFFF; background-color:#54B944; border-radius: 0px;margin-top:5px;color:white" />
	</div>
</div>
</form>
<?php endforeach; ?>
</div>

<script>
	$('#str').on('change', function(event){
		event.preventDefault();   
		  var $idstr = $(this).val();  

  		if(history.pushState) {
    		history.pushState(null, null, '/gidop/public/' );
			$('#loaddossier').load('reaction/loaddossier',{idstr : $idstr})
  		}
 
  		return false;

	})
		

</script>
